services:
  simplewebapi:
    build:
      context: "../src/SimpleWebApi"
      dockerfile: "SimpleWebApi/Dockerfile"
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      SQL_SERVER_SA_PASSWORD: ${SQL_SERVER_SA_PASSWORD}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQL_SERVER_SA_PASSWORD}
