services:
  simplewebapi:
    build:
      context: "../src/SimpleWebApi"
      dockerfile: "SimpleWebApi/Dockerfile"
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DATABASE_CONNECTION_STRING: "Data Source=sqlserver;Initial Catalog=SimpleDatabase;User id=SA;Password=${SQL_SERVER_SA_PASSWORD};TrustServerCertificate=True;"
    networks:
      - devenv-network

  sqlserver:
    build: "database"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQL_SERVER_SA_PASSWORD}
    networks:
      - devenv-network

networks:
  devenv-network:
    name: devenv-network
    driver: bridge
