openapi: 3.0.1
info:
  title: SimpleWebApi!!!!!
  description: API for retrieving weather forecasts.
  version: 1.0.0
paths:
  /WeatherForecast:
    get:
      summary: Get Weather Forecast
      description: Returns a list of weather forecasts for the next 5 days.
      operationId: GetWeatherForecast
      tags:
        - WeatherForecast
      responses:
        '200':
          description: A list of weather forecasts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
          description: The date of the forecast.
        temperatureC:
          type: integer
          description: The temperature in Celsius.
        temperatureF:
          type: integer
          description: The temperature in Fahrenheit.
        summary:
          type: string
          description: A summary of the weather conditions.
