name: Contract Test CI

on:
  push:
    paths:
      - "open-api-definitions/*.yaml"

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint OpenAPI Spec using Spectral
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: open-api-definitions/*.yaml

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Web API in background
        run: |
          dotnet build src/SimpleWebApi/SimpleWebApi/SimpleWebApi.csproj
          dotnet run --project src/SimpleWebApi/SimpleWebApi/SimpleWebApi.csproj --urls "http://localhost:5183" &

          # Pause to allow the Web API to start
          sleep 10

      - name: Contract test using Specmatic
        uses: airslate-oss/setup-specmatic@v1
        with:
          specmatic-version: '>=2.11.0'
      - run: specmatic test "open-api-definitions/simple-web-api.yaml" --testBaseURL='http://127.0.0.1:5183'

      - name: Upload Specmatic HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: specmatic-report
          path: build/reports/specmatic/html/

# Failed attempt to run via Docker ("connection refused" error).
# 172.17.0.1 is the default IP address for the Docker host in Linux environments.
# docker run -v "$(pwd)/open-api-definitions/simple-web-api.yaml:/simple-web-api.yaml" znsio/specmatic test "/simple-web-api.yaml" --testBaseURL=http://172.17.0.1:5183
