name: Contract Test CI

on:
  push:
    paths:
      - "open-api-definitions/*.yaml"

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Web API in background
        run: |
          dotnet run src/SimpleWebApi/SimpleWebApi/SimpleWebApi.csproj --urls "http://localhost:5183" &

      - name: Contract test using Specmatic
        run: |
          docker run -v "$(pwd)/open-api-definitions/simple-web-api.yaml:/simple-web-api.yaml" znsio/specmatic test "/simple-web-api.yaml" --testBaseURL=http://host.docker.internal:5183
