name: hello-world

# Trigger even for running action!
# TODO: Can we fine tune this to specific paths?
# TODO: Can we fine tune this so it only fires if non-markdown files are changed?

#on: push

#  push:
#    branches:
#      - "main"
#    paths:
#      - "src"
#paths-ignore:
#  - '**/*.md'

on:
  push:
    paths:
      - "src/**"

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - run: echo "hello world!"
