name: hello-world

on:
  push:
    paths:
      # Only trigger for changes in "src" folder
      - "src/**"
      # Do not trigger CI for changes to markdown (*.md) files
      - "!**/*.md"

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - run: echo "hello world!"
