name: SimpleWebApi CI Build

on:
  push:
    paths:
      # Only trigger for changes in "SimpleWebApi" project folder
      - "src/SimpleWebApi/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: src/SimpleWebApi/SimpleWebApi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: $WORKING_DIR

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: $WORKING_DIR

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: $WORKING_DIR
